<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hotelariaDSL" nsURI="hotelariaDSL" nsPrefix="hotelariaDSL">
  <eClassifiers xsi:type="ecore:EClass" name="Super" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hospede" eSuperTypes="#//Super">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contaBanco" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recepcionista" eSuperTypes="#//Super"/>
  <eClassifiers xsi:type="ecore:EClass" name="Quarto" eSuperTypes="#//Super"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuartoSolteiro" eSuperTypes="#//Quarto"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuartoComunitario" eSuperTypes="#//Quarto"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuartoCasal" eSuperTypes="#//Quarto"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacao">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="TipoQuartoInvalido"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Super" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomeAtributo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
